
runtime: nodejs16

instance_class: F2

env_variables:
  BUCKET_NAME: "glambeauty"

handlers:
- url: /
  static_files: dist/frontend-recruitment-test/index.html
  upload: dist/frontend-recruitment-test/index.html

- url: /
  static_dir: dist/frontend-recruitment-test
