steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - gcr.io/$PROJECT_ID/frontend-recruitment-test
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - gcr.io/$PROJECT_ID/frontend-recruitment-test
  - name: gcr.io/cloud-builders/gcloud
    args:
      - beta
      - run
      - deploy
      - '--allow-unauthenticated'
      - $PROJECT_ID
      - '--image'
      - gcr.io/$PROJECT_ID/frontend-recruitment-test
      - '--region'
      - us-central1
      - '--platform'
      - managed
      - '--memory'
      - 128Mi
images:
  - gcr.io/$PROJECT_ID/frontend-recruitment-test
